
// Generated by Cadence Genus(TM) Synthesis Solution 20.10-p001_1
// Generated on: Jul 30 2025 16:28:24 IST (Jul 30 2025 10:58:24 UTC)

// Verification Directory fv/s27 

module dff(CK, Q, D, RS);
  input CK, D, RS;
  output Q;
  wire CK, D, RS;
  wire Q;
  wire n_0;
  DFFHQX1 Q_reg(.CK (CK), .D (n_0), .Q (Q));
  NOR2BX1 g4(.AN (D), .B (RS), .Y (n_0));
endmodule

module dff_4(CK, Q, D, RS);
  input CK, D, RS;
  output Q;
  wire CK, D, RS;
  wire Q;
  wire n_0;
  DFFHQX1 Q_reg(.CK (CK), .D (n_0), .Q (Q));
  NOR2BX1 g4(.AN (D), .B (RS), .Y (n_0));
endmodule

module dff_3(CK, Q, D, RS);
  input CK, D, RS;
  output Q;
  wire CK, D, RS;
  wire Q;
  wire n_0;
  DFFHQX1 Q_reg(.CK (CK), .D (n_0), .Q (Q));
  NOR2BX1 g4(.AN (D), .B (RS), .Y (n_0));
endmodule

module s27(CK, G0, G1, G17, G2, G3);
  input CK, G0, G1, G2, G3;
  output G17;
  wire CK, G0, G1, G2, G3;
  wire G17;
  wire G5, G6, G7, G10, G11, G13, UNCONNECTED, UNCONNECTED0;
  wire UNCONNECTED1, n_0, n_1, n_2;
  dff DFF_0(CK, G5, G10, UNCONNECTED);
  dff_4 DFF_1(CK, G6, G11, UNCONNECTED0);
  dff_3 DFF_2(CK, G7, G13, UNCONNECTED1);
  INVXL g2(.A (G11), .Y (G17));
  NOR2BX1 g59(.AN (G0), .B (G11), .Y (G10));
  NOR2XL g60(.A (G5), .B (n_2), .Y (G11));
  AOI22XL g61(.A0 (G3), .A1 (n_1), .B0 (n_0), .B1 (G6), .Y (n_2));
  NOR2XL g62(.A (G2), .B (n_1), .Y (G13));
  NOR2XL g63(.A (G1), .B (G7), .Y (n_1));
  INVXL g64(.A (G0), .Y (n_0));
endmodule

